### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by helenypzhang** [razorx89/roco-dataset#10]
Hi, I tried the download code, but it always shows: retrying even with setting -n 1

(base) [yupei@login roco-dataset-master]$ python scripts/fetch.py
Configuration:
Subdirectory: images
Extraction directory: /tmp/roco-dataset
Keep archives: False
Delete contents of extraction directory: False
Number of processes: 64
Number of download retries: 10
Fetching ROCO dataset images...
Error: download failed, retrying
Trying to get new archive URL: https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi?tool=roco-fetch&email=johannes.rueckert@fh-dortmund.de&id=PMC3395713
Error: download failed, retrying
Trying to get new archive URL: https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi?tool=roco-fetch&email=johannes.rueckert@fh-dortmund.de&id=PMC3130474

Could you tell me why?
THX

**Comment by saviola777** [comment]
Hello, to me it looks like these particular archives have been moved to a different location. So this is not really a problem: The script simply gets the new archive URL and downloads it from there. Maybe the error message could be more clear.

**Comment by helenypzhang** [comment]
> I hope so, but it seems that after the code  retrying 10 time, I still got failed download message. Maybe I should try it again. Thank you for your reply.

**Comment by saviola777** [comment]
I see, maybe you can post the full output of the script (at least all parts with error messages)?

**Comment by helenypzhang** [comment]
> 
It works after I retrying it several times. Processing get stuck when 57% of images are downloaded successfully. But I think it will succeed.
Thank you so much!
