### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by PranjalSahu** [razorx89/roco-dataset#11]
Is the script still working ? Or something has changed ?
I tried with 1 process also and it failed after 10 attempts.

**Comment by saviola777** [comment]
I just tested it and it still seems to work. Can you show the output of the script? Does it fail right away or does it manage to download some images before failing? Does it always fail at the same images? It might be similar to #10.

**Comment by PranjalSahu** [comment]
It worked for me on the Ubuntu system, so closing the issue.
