### ISSUE TITLE
slow speed 

### ISSUE THREAD

**Issue by lixiaoqingnnz** [razorx89/roco-dataset#13]
Hi thank you so much for your work!

May I ask is it normal that the download speed is very slow? It takes about 10 seconds to download one image. The command I used was: python fetch.py -n 1 
Because if the number of processes is 10, then many error would occurred.

Thanks

**Comment by saviola777** [comment]
The PMC FTP can be slow or stall sometimes, but I have not yet seen consistently low speeds like that. I don't see anything we can do on our end, you could try it with a VPN/Proxy or from a different intermediate server. I think we've had a number of reports of slow or failing downloads in the issues here. If you find a solution please post it here.
