### ISSUE TITLE
filename 'PMC4889020/nihms790182f4.jpg' not found"    

### ISSUE THREAD

**Issue by JOY-SWang** [razorx89/roco-dataset#14]
some pictures cannot  be downloaded. 
Error: failed to extract image PMC4889020/nihms790182f4.jpg from archive ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/da/a9/PMC4889020.tar.gz: "filename 'PMC4889020/nihms790182f4.jpg' not found"                                                                   Image PMC4889020/nihms790182f4.jpg not found in archive ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/da/a9/PMC4889020.tar.gz, skipping

**Comment by saviola777** [comment]
That's correct, the image is no longer contained in that archive, the archive has probably been updated. Not much we can do about it.
