### ISSUE TITLE
I don't know how to complete the download?

### ISSUE THREAD

**Issue by languandong** [razorx89/roco-dataset#15]
I run the script "python scripts/fetch.py".
But it downloaded as 9.895%.
![image](https://github.com/razorx89/roco-dataset/assets/44127403/d5319b22-251b-402e-b580-05fb086ec824)
So I immediately re-executed the script.
![image](https://github.com/razorx89/roco-dataset/assets/44127403/e479ec5c-aaf3-4bba-8e48-aa28f9212b4f)
Should I take -d at the end of this instruction?

**Comment by saviola777** [comment]
Did the script abort after the errors in the first screenshot? Usually it should just continue even if some images are no longer available (which is to be expected after 5+ years). If you pass `-d` it will delete the images you have downloaded so far.

For an alternative dataset, you might want to check out [ROCOv2](https://zenodo.org/records/8333645).

**Comment by languandong** [comment]
> Did the script abort after the errors in the first screenshot? Usually it should just continue even if some images are no longer available (which is to be expected after 5+ years). If you pass `-d` it will delete the images you have downloaded so far.
> 
> For an alternative dataset, you might want to check out [ROCOv2](https://zenodo.org/records/8333645).

This V2's form is so convenient. I like it!
Maybe V1 can also be organized like this

**Comment by biegekekeke** [comment]
> Did the script abort after the errors in the first screenshot? Usually it should just continue even if some images are no longer available (which is to be expected after 5+ years). If you pass `-d` it will delete the images you have downloaded so far.
> 
> For an alternative dataset, you might want to check out [ROCOv2](https://zenodo.org/records/8333645).

Why doesn't v2 have keywords anymore?

**Comment by saviola777** [comment]
Good question! In the end you can probably generate keywords using the concept CUIs plus the concept names. Maybe we will add keywords at a later stage, thanks for the suggestion.

**Comment by biegekekeke** [comment]
> Good question! In the end you can probably generate keywords using the concept CUIs plus the concept names. Maybe we will add keywords at a later stage, thanks for the suggestion. 好问题！最后，你可以使用概念CUIs加上概念名称来生成关键字。也许我们会在后期添加关键词，谢谢建议。

Oh, yes, I have incorporated CUIs along with concept names to generate keywords. Thank you for your help.

**Comment by biegekekeke** [comment]
> Good question! In the end you can probably generate keywords using the concept CUIs plus the concept names. Maybe we will add keywords at a later stage, thanks for the suggestion.

Oh, yes, I have incorporated CUIs along with concept names to generate keywords. Thank you for your help.
