### ISSUE TITLE
Error: download failed, retrying

### ISSUE THREAD

**Issue by shixinlishixinli** [razorx89/roco-dataset#16]
my environment has proxy
i can not download any image of dataset.  but i can download other txt file of the dataset.

python scripts/fetch.py -n 1
Configuration:
Subdirectory: images
Extraction directory: /tmp/roco-dataset
Keep archives: False
Delete contents of extraction directory: False
Number of processes: 1
Number of download retries: 10
Fetching ROCO dataset images...
Error: download failed, retrying
Trying to get new archive URL: https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi?tool=roco-fetch&email=johannes.rueckert@fh-dortmund.de&id=PMC4608653
Error: download failed, retrying
Error: download failed, retrying
Error: download failed, retrying
Error: download failed, retrying
Error: download failed, retrying

"""
Traceback (most recent call last):
  File "/home/work/lisa/miniconda3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/work/lisa/distributed/visual-med-alpaca/roco-dataset/scripts/fetch.py", line 151, in process_group
    result = download_archive(extraction_dir_name, archive_url,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/lisa/distributed/visual-med-alpaca/roco-dataset/scripts/fetch.py", line 212, in download_archive
    raise Exception("Giving up download of archive {0} after {1} tries"
Exception: Giving up download of archive ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/8d/34/PMC4608653.tar.gz after 11 tries
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/work/lisa/distributed/visual-med-alpaca/roco-dataset/scripts/fetch.py", line 338, in <module>
    pool = multiprocessing.Pool(processes=args.num_processes,
  File "/home/work/lisa/miniconda3/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
Exception: Giving up download of archive ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/8d/34/PMC4608653.tar.gz after 11 tries

**Comment by saviola777** [comment]
Not much I can do about this, there seems to be an issue connecting to the PubMed FTP from your side. As I said in another issue, maybe try to use [ROCOv2](https://zenodo.org/records/8333645) instead.
