### ISSUE TITLE
dataset issues

### ISSUE THREAD

**Issue by Allenxq** [razorx89/roco-dataset#7]
Does the image name of the downloaded data set match the name of the image corresponding to the caption? How can I solve it, or can I directly provide a link to the data set?Thanks!

**Comment by saviola777** [comment]
No, it did not match the IDs, and I'm not sure why. But now it does! Let me know if this fixes your problem.

**Comment by Allenxq** [comment]
![50A JZZHM~L AD~@4YZ`%HQ](https://user-images.githubusercontent.com/50684600/148235352-7573f6ae-0bb4-446f-a3f5-405b2d9de27f.png)
I think it should be in the licenses file. There is a one-to-one correspondence between the image name of the downloaded dataset and the image name corresponding to the caption in the captions. Therefore, I think it is enough to modify the image name according to this. Hope this is correct, thank you for your reply, thank you!

**Comment by Allenxq** [comment]
I think it should be in the licenses file. There is a one-to-one correspondence between the image name of the downloaded dataset and the image name corresponding to the caption in the captions. Therefore, I think it is enough to modify the image name according to this. Hope this is correct, thank you for your reply, thank you!
![image](https://user-images.githubusercontent.com/50684600/148236010-f190a4e2-8178-4702-9b31-6e4db0f3401e.png)

**Comment by saviola777** [comment]
Ah yes, you are correct. That was about the only file I did not check. I am closing the issue then, since you have found a solution if I understand you correctly? For people who download it in the future, the extracted image names will correspond to the ROCO ID instead, so that matching the captions, CUIs etc. will be easier.
