### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by S200331082** [razorx89/roco-dataset#8]
hi there, I ran `fetch.py` under the [Unbuntu On WSL](url), got some problems, here is the traceback:

```
Configuration:
Subdirectory: images
Extraction directory: /tmp/roco-dataset
Keep archives: False
Delete contents of extraction directory: False
Number of processes: 12
Number of download retries: 10
Fetching ROCO dataset images...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "fetch.py", line 199, in process_group
    shutil.copy(image_filename, target_filename)
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/radiology/images/ROCO_00176.jpg'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fetch.py", line 340, in <module>
    for i, pmc_id in enumerate(pool.imap_unordered(process_group,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/radiology/images/ROCO_00176.jpg'
```

I don't sure how's that happening? I also trying to run `fetch.py` in Windows, at beginning it works for a little while, some pics download in `images` indeed, but then thrown errors like:
`zlib.error: Error -3 while decompressing data: invalid stored block lengths`
`module gzip has no attribute BadGzip` etc.

could you give me some fixing ways, appreciated for it.

**Comment by saviola777** [comment]
Hello, have you tried setting the number of processes to 1? It will take longer, but this reduces the chance of the downloads failing (which I'm assuming causes the issues). Let me know if you still have problems using 1 process, then I'll see if it's a Windows/WSL problem or if some new problem with the API has appeared.

**Comment by S200331082** [comment]
thanks for reply
> have you tried setting the number of processes to 1? 

Windows: yes, still the errors I've mentioned.
WSL: not yet, forget to try.
I will try it tomorrow on WSL and reply soon, time to sleep, GN:)

**Comment by S200331082** [comment]
WSL: setting the number of processes to 1

> s200331082@DESKTOP-LG7KM5A:/mnt/c/Users/fhdu/PycharmProjects/roco-dataset-master/scripts$ python3 fetch.py -n 1
Configuration:
Subdirectory: images
Extraction directory: /tmp/roco-dataset
Keep archives: False
Delete contents of extraction directory: False
Number of processes: 1
Number of download retries: 10
Fetching ROCO dataset images...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "fetch.py", line 199, in process_group
    shutil.copy(image_filename, target_filename)
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/radiology/images/ROCO_00001.jpg'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "fetch.py", line 340, in <module>
    for i, pmc_id in enumerate(pool.imap_unordered(process_group,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/radiology/images/ROCO_00001.jpg'

same issues.

**Comment by saviola777** [comment]
Ah, you are running the script from the wrong directory. Please try it like shown in the README, like `python3 scripts/fetch.py` from the root directory of the repository.

**Comment by razorx89** [comment]
@saviola777 You could maybe add a check based on the `__file__` attribute.

**Comment by saviola777** [comment]
As suggested, the directory is now resolved using the `__file__` attribute, making it possible to call the script from any directory. I'm closing this issue assuming that you got it to work, @S200331082, please re-open if that is not the case.
